---
defaults:
    port: 8765
routes:
    -
        method: GET
        path: /test/text
        string: "Data"
    -
        method: GET
        path: /hello/miljane
        file: "../../examples/test.json"
    -
        method: GET
        path: /test/python
        ignoreSlash: true
        command: "python ../../examples/hello.py"
#            arguments:
#                - %path%
#                - %body%

#routes:
#    KeyValuePut:
#        method: PUT
#        path: /{key}
#        escapeSlash: true #If set to true path "/{key}" will match "/something" as well as "/something/else"
#        response: "Hello World"
#    KeyValueGet:
#        method: GET
#        path: /{(.*)}
#routes:
#    -
#        method: GET
#        path: /first
#        output: "First"
#    -
#        method: GET
#        path: /second/{clientId}
#        output: bash.sh
#        arguments:
#            {{url}}
#            {{method}}
#            {{clientId}}
#            {{dc}}
#    -
#        method: GET
#        path: /lazar
#        output: handleTHatRoute
#    -
#        method: GET
#        path: /second/{clientId}
#        response:
#            script: bash.sh (stdout, stderr = za HTTP status kodove)
#                arguments:
#                    {{url}}
#                    {{method}}
#                    {{clientId}}
#                    {{dc}}
#            string: